"""add tables

Revision ID: 4f64ba495242
Revises: 
Create Date: 2023-06-29 00:11:42.331677

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4f64ba495242'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VAD_divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VAD_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('patronymic', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VAD_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VAD_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('date_of_employment', sa.String(), nullable=False),
    sa.Column('date_of_dismissal', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['VAD_divisions.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['VAD_employees.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['VAD_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VAD_jobs')
    op.drop_table('VAD_positions')
    op.drop_table('VAD_employees')
    op.drop_table('VAD_divisions')
    # ### end Alembic commands ###